[package]
name = 'deployer'
version = '1.0.0'

[addresses]
AptosFramework = "0x1"
deployer = "0x5a5e124ea1f3fc5fcfae3c198765c3b4c8d72c7236ae97ef6e5a9bc7cfda549c"

[dev-addresses]
deployer = "0x12345"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'aptos-cli-v1.0.0'
subdir = 'aptos-move/framework/aptos-framework'
